spring:
  profiles:
    active: postgresql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # N+1 问题，批量查询的量，用in代替，较少sql查询的次数
        default_batch_fetch_size: 100
        jdbc:
          #每批500条提交
          batch_size: 500
          batch_versioned_data: true
          order_inserts: true
          order_updates: true


server:
  port: 9919


#配置actuator，开启所有endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true



#配置log等级
logging:
  file:
    path: ./log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    #    org.hibernate.type..descriptor.sql.BasicBinder: trace
    druid.sql.Statement: DEBUG